apiVersion: v1
kind: Namespace
metadata: { name: spark }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels: { app: spark, role: master }
spec:
  replicas: 1
  selector: { matchLabels: { app: spark, role: master } }
  template:
    metadata: { labels: { app: spark, role: master } }
    spec:
      containers:
        - name: master
          image: apache/spark:3.5.1
          env:
            - { name: SPARK_MASTER_PORT, value: "7077" }
            - { name: SPARK_MASTER_WEBUI_PORT, value: "8080" }
            - { name: SPARK_MASTER_HOST, valueFrom: { fieldRef: { fieldPath: status.podIP } } }
            - { name: SPARK_NO_DAEMONIZE, value: "1" }
            - name: SPARK_DAEMON_JAVA_OPTS
              value: >
                -Dspark.ui.reverseProxy=true
                -Dspark.ui.proxyRedirectUri=http://spark.local
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
            - name: SPARK_PUBLIC_DNS
              value: spark.local
          command: ["/bin/bash","-lc"]
          args:
            - |
              exec /opt/spark/sbin/start-master.sh \
                --host ${SPARK_MASTER_HOST} \
                --port ${SPARK_MASTER_PORT} \
                --webui-port ${SPARK_MASTER_WEBUI_PORT}
          ports:
            - { containerPort: 7077 }
            - { containerPort: 8080 }
